services:
## BACKEND (Node + Express) ##
  backend:
    build: ./backend
    container_name: bluecheck-backend
    restart: unless-stopped
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "3002:3002"
    depends_on:
      - db
  
  ## FRONTEND (React) ##
  frontend:
    container_name: bluecheck-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:5173"
    volumes:
      - ./frontend:/usr/src/app
      - ./frontend/coverage:/usr/src/app/coverage
      - /usr/src/app/node_modules
    command: npm run dev

  ## BASE DE DATOS (PostgreSQL 18) ##
  db:
    image: postgis/postgis:18-3.6
    container_name: bluecheck-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  ## ADMINER (Gestor visual de la base de datos) ##
  adminer:
    image: adminer
    container_name: bluecheck-adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - db
  
  ## Node Proxy Manager ##
  npm:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - npm_data:/data
      - npm_letsencrypt:/etc/letsencrypt

  ## SonarQube ##
  sonarqube:
    image: sonarqube:community
    container_name: bluecheck-sonarqube
    depends_on:
      - sonar-db
    ports:
      - "9000:9000"
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonar-db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs

  ## Sonarqube Database ##
  sonar-db:
    image: postgres:18
    container_name: bluecheck-sonar-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    volumes:
      - sonar_postgres_data:/var/lib/postgresql

  ## Sonar Scanner Frontend ##
  ## Descomentar en caso de querer ejecutar los análisis
  # sonar-frontend:
  #   image: sonarsource/sonar-scanner-cli
  #   container_name: bluecheck-sonar-frontend
  #   depends_on:
  #     - sonarqube
  #   environment:
  #     SONAR_HOST_URL: http://sonarqube:9000
  #     SONAR_TOKEN: ${SONAR_TOKEN}
  #   volumes:
  #     - ./frontend:/usr/src
  #   working_dir: /usr/src
  
  ## Sonar Scanner Backend ##
  ## Descomentar en caso de querer ejecutar los análisis
  # sonar-backend:
  #   image: sonarsource/sonar-scanner-cli
  #   container_name: bluecheck-sonar-backend
  #   depends_on:
  #     - sonarqube
  #   environment:
  #     SONAR_HOST_URL: http://sonarqube:9000
  #     SONAR_TOKEN: ${SONAR_TOKEN}
  #   volumes:
  #     - ./backend:/usr/src
  #   working_dir: /usr/src
      
volumes:
  postgres_data:
  npm_data:
  npm_letsencrypt:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  sonar_postgres_data: